### ISSUE TITLE
iPhone 11 Pro Overheating

### ISSUE THREAD

**Issue by psaravan** [DanielVolt/Velox-Issue-Tracker#11] opened 2020-03-01 16:01 UTC
Created a couple of widgets (Calendar, Activity, Weather and Reminders). My iPhone 11 Pro gets very hot to the touch on the rear of the phone. The issue goes away after I uninstall Volex so it appears to be coming from this tweak. I did not have any issues before installing this tweak. Let me know if/how I can provide logs or other debugging aritfacts to help investigate this issue.

**Comment by DanielVolt** [comment] 2020-03-01 16:02
Thank you for reporting, i'll get right on this to make sure this issue is resolved in the upcoming update

**Comment by 0cyn** [comment] 2020-03-03 07:52
Although originally we thought this may have been a compatibility issue, phone temperature is _nearly_ impossible to accurately measure. 

Over the past few days this tweak has received massive optimizations in several areas. I can confirm that I also dealt with abnormal heating of my phone, and I can currently confirm that v1.0.1 does not cause this at all. 

Since again, phone temperature is a hard thing to test/measure, once the latest build has been released please let us know if it seems to fix the heating issue.

**Comment by DanielVolt** [comment] 2020-04-06 16:58
As we rewrote Velox's widget manager for 1.1, no user experienced any lag or overheating. Update to 1.1

**Closed as completed by DanielVolt** 2020-04-06 16:58 UTC
Labels: good first issue
